- Android/res/values-it/strings.xml
- Android/res/xml-it/checklist_default.xml
> Improved italian translations

- Android/build.gradle
- Android/res/values/strings.xml
> Updated the name from DroidPlanner 3 to Tower

- Android/build.gradle
- Android/res/layout/fragment_mode_follow.xml
- Android/res/values/preferences_keys.xml
- Android/res/values/strings.xml
- Android/src/org/droidplanner/android/activities/FlightActivity.java
- Android/src/org/droidplanner/android/activities/helpers/BluetoothDevicesActivity.java
- Android/src/org/droidplanner/android/dialogs/ClearBTDialogPreference.java
- Android/src/org/droidplanner/android/fragments/DroneMap.java
- Android/src/org/droidplanner/android/fragments/SettingsFragment.java
- Android/src/org/droidplanner/android/fragments/mode/FlightModePanel.java
- Android/src/org/droidplanner/android/fragments/mode/ModeFollowFragment.java
- Android/src/org/droidplanner/android/graphic/map/GuidedScanROIMarkerInfo.java
- Android/src/org/droidplanner/android/utils/prefs/DroidPlannerPrefs.java
* Added `Guided Scan` follow mode. 
* Fixed bluetooth connection issue.
> Version 3.0.14

- Android/build.gradle
- Android/res/layout/fragment_mode_follow.xml
- Android/src/org/droidplanner/android/fragments/mode/ModeFollowFragment.java
* Added GUIDED SCAN follow me mode description.
> Version 3.0.15

- Android/build.gradle
- Android/res/drawable/button_mission_default.xml
- Android/res/drawable/button_mission_selected.xml
- Android/res/layout/fragment_editor_list_item.xml
- Android/res/layout/fragment_mode_follow.xml
- Android/res/values/strings.xml
- Android/src/org/droidplanner/android/activities/EditorActivity.java
- Android/src/org/droidplanner/android/fragments/EditorListFragment.java
- Android/src/org/droidplanner/android/fragments/mode/ModeFollowFragment.java
- Android/src/org/droidplanner/android/graphic/map/GuidedScanROIMarkerInfo.java
- Android/src/org/droidplanner/android/utils/prefs/DroidPlannerPrefs.java
- Android/src/org/droidplanner/android/utils/unit/UnitManager.java
Version 3.0.16
* Added ability to modify the GUIDED SCAN follow mode roi altitude.
> Version 3.0.16

- Android/build.gradle
- Android/src/org/droidplanner/android/fragments/EditorToolsFragment.java
- Android/src/org/droidplanner/android/fragments/FlightMapFragment.java
- Android/src/org/droidplanner/android/fragments/ParamsFragment.java
> Version 3.0.17

- Android/build.gradle
- Android/src/org/droidplanner/android/fragments/SensorSetupFragment.java
- Android/src/org/droidplanner/android/utils/prefs/DroidPlannerPrefs.java
- README.md
Tower v3.1.0 stable release:
* Removed compass calibration for final release.
> Version 3.1.0

- Android/build.gradle
- Android/res/layout/fragment_editor_detail_generic.xml
- Android/res/values/strings.xml
- Android/src/org/droidplanner/android/activities/EditorActivity.java
- Android/src/org/droidplanner/android/fragments/account/DroneshareAccountFragment.java
- Android/src/org/droidplanner/android/fragments/account/DroneshareLoginFragment.java
- Android/src/org/droidplanner/android/proxy/mission/MissionProxy.java
- Android/src/org/droidplanner/android/proxy/mission/item/MissionItemProxy.java
- Android/src/org/droidplanner/android/proxy/mission/item/fragments/MissionDetailFragment.java
- Android/src/org/droidplanner/android/utils/collection/CircularQueue.java
Version 3.1.1 changelog:
* Fixed 'undo' crash bugs, and glitches.
* Fixed crash bug caused by changing command mission items to waypoints.
* Fixed invalid toast message when failing to login to Droneshare.
> Version 3.1.1

- Android/res/layout/popup_info_gps.xml
- Android/src/org/droidplanner/android/fragments/actionbar/ActionBarTelemFragment.java
I've added a GPS popup similar to the signal strength popup, so that I can see the number of satellites and HDOP when I received PreArm errors on HDOP. Others might find this useful as well.
> Added GPS popup

- Android/build.gradle
- Android/res/layout/fragment_rover_mission_control.xml
- Android/res/values/strings.xml
- Android/src/org/droidplanner/android/fragments/FlightActionsFragment.java
- Android/src/org/droidplanner/android/fragments/RoverFlightActionsFragment.java
- Android/src/org/droidplanner/android/fragments/mode/FlightModePanel.java
- Android/src/org/droidplanner/android/fragments/mode/ModeGuidedFragment.java
- Android/src/org/droidplanner/android/maps/providers/google_map/GoogleMapFragment.java
- Android/src/org/droidplanner/android/proxy/mission/MissionProxy.java
Merging the changes for `release 3.1.5` into the `develop` branch.
This is unorthodox, as typically the `release-3.1.5` branch should have been branched off the latest from `develop` and only merge back (if needed) when released to production.
Future merges shall revert back to the standard branching model.
> Release 3.1.5

- Android/build.gradle
- Android/res/values/preferences_keys.xml
- Android/res/values/strings.xml
- Android/res/xml/preferences.xml
- Android/src/org/droidplanner/android/DroidPlannerApp.java
- Android/src/org/droidplanner/android/fragments/SettingsFragment.java
- Android/src/org/droidplanner/android/utils/prefs/DroidPlannerPrefs.java
Add front-end support for a UDP ping.
> Feature UDP Client connection

- Android/build.gradle
https://github.com/DroidPlanner/Tower/releases/tag/Tower-v3.1.6
> Release 3.1.6

- Android/src/org/droidplanner/android/fragments/ParamsFragment.java
I can't be the only person who this annoyed
> Make search bar clickable

- Android/res/values-sw540dp/styles.xml
- Android/res/values/dimens.xml
> updated gravity for the bottom control bar.

- Android/src/org/droidplanner/android/utils/unit/providers/speed/ImperialSpeedUnitProvider.java
> Changed the default speed unit from ft/s to mph.

- Android/build.gradle
- Android/res/values/strings.xml
- Android/src/org/droidplanner/android/fragments/ParamsFragment.java
- Android/src/org/droidplanner/android/widgets/adapterViews/ParamsAdapter.java
> Add snackbar notification when parameters not saved

- Android/res/values-zh-rCN/strings.xml
> Update Chinese(simplified) translation

- .travis.yml
* Update the travis ci configuration file to take advantage of their new infrastructure.
* Increased the amount of memory allocated to the build process.
> Travis ci configuration update

- Android/res/values-fr/strings.xml
Hi,
Here is the french translate of the App. Based line by line from the English strings.xml.
Compiled, spell checked, verified with the tablet for all visible characters and checked words lengths to fit the graphical design.
It is ver 1.0, any french contributor is welcome !
> Tower French Translate.

- Android/build.gradle
- Android/res/layout/fragment_editor_detail_change_speed.xml
- Android/res/xml/preferences.xml
- Android/src/org/droidplanner/android/activities/WidgetActivity.kt
- Android/src/org/droidplanner/android/dialogs/SlideToUnlockDialog.java
- Android/src/org/droidplanner/android/fragments/EditorToolsFragment.java
- Android/src/org/droidplanner/android/fragments/SettingsFragment.java
- Android/src/org/droidplanner/android/fragments/control/CopterFlightControlFragment.java
- Android/src/org/droidplanner/android/fragments/mode/ModeGuidedFragment.java
- Android/src/org/droidplanner/android/proxy/mission/item/fragments/MissionDetailFragment.java
- Android/src/org/droidplanner/android/proxy/mission/item/fragments/MissionStructureScannerFragment.java
- Android/src/org/droidplanner/android/proxy/mission/item/fragments/MissionSurveyFragment.java
- Android/src/org/droidplanner/android/utils/prefs/DroidPlannerPrefs.java
- Android/src/org/droidplanner/android/widgets/adapterViews/MissionItemListAdapter.java
> Release 3.2.0 bug fixes

- Android/src/org/droidplanner/android/fragments/actionbar/ActionBarTelemFragment.java
- Android/src/org/droidplanner/android/notifications/TTSNotificationProvider.java
Ardupilot ublox driver already report 3D+DGPS. Tower should support all possible status values https://github.com/diydrones/ardupilot/blob/master/libraries/AP_GPS/AP_GPS.h#L95.
> Add 3D+DGPS and 3D+RTK gps fix status

- Android/res/values-de/strings.xml
- Android/res/values-fr/strings.xml
- Android/res/values-it/strings.xml
- Android/res/values-zh-rCN/strings.xml
- Android/res/values-zh-rTW/strings.xml
- Android/res/values/strings.xml
- Android/res/xml/preferences.xml
- Android/src/org/droidplanner/android/notifications/TTSNotificationProvider.java
- Android/src/org/droidplanner/android/utils/ReorderRecyclerView.java
- Android/src/org/droidplanner/android/utils/prefs/DroidPlannerPrefs.java
> Custom max altitude warning

- Android/src/org/droidplanner/android/fragments/mode/ModeFollowFragment.java
- Android/src/org/droidplanner/android/proxy/mission/item/fragments/MissionCameraTriggerFragment.java
- Android/src/org/droidplanner/android/proxy/mission/item/fragments/MissionCircleFragment.java
- Android/src/org/droidplanner/android/proxy/mission/item/fragments/MissionStructureScannerFragment.java
- Android/src/org/droidplanner/android/proxy/mission/item/fragments/MissionSurveyFragment.java
- Android/src/org/droidplanner/android/utils/Utils.java
> Updated min / max distance for the mission items' radius

- Android/src/org/droidplanner/android/activities/helpers/MapPreferencesActivity.java
- Android/src/org/droidplanner/android/fragments/DroneMap.java
- Android/src/org/droidplanner/android/fragments/EditorMapFragment.java
- Android/src/org/droidplanner/android/fragments/FlightMapFragment.java
- Android/src/org/droidplanner/android/fragments/mode/ModeGuidedFragment.java
- Android/src/org/droidplanner/android/notifications/TTSNotificationProvider.java
Fixed crash when attempting to enable the mapbox provider.
> Fixed fast repetition of max altitude exceeded warnings.

- Android/src/org/droidplanner/android/DroidPlannerApp.java
- Android/src/org/droidplanner/android/notifications/EmergencyBeepNotificationProvider.java
- Android/src/org/droidplanner/android/notifications/NotificationHandler.java
- Android/src/org/droidplanner/android/notifications/StatusBarNotificationProvider.java
- Android/src/org/droidplanner/android/notifications/TTSNotificationProvider.java
> Fixed persistent notification.

- Android/res/layout/fragment_mini_widget_telemetry_info.xml
- Android/res/values/strings.xml
- Android/src/org/droidplanner/android/fragments/widget/MiniWidgetTelemetryInfo.kt
Added latitude and longitude data to the telemetry widget.
> Add Latitude and Longitude to telemetry widget

- Android/build.gradle
- Android/src/org/droidplanner/android/DroidPlannerApp.java
- README.md
> Release 3.2.0 beta 7

- Android/src/org/droidplanner/android/activities/helpers/SuperUI.java
kill switch menu should be available only when:
+ kill switch preference checked
+ drone support the kill switch feature
> kill switch menu should not always available

- build.gradle
This fix the build error when the gradle properties file is not setup correctly.
> Add default maven repo url. 

- Android/src/org/droidplanner/android/proxy/mission/item/MissionItemProxy.java
Adding the consideration of the number of turns add a better length estimation of the circle.
> Better circle length calculation

- Android/src/org/droidplanner/android/proxy/mission/item/fragments/MissionCircleFragment.java
- Android/src/org/droidplanner/android/proxy/mission/item/fragments/MissionStructureScannerFragment.java
- Android/src/org/droidplanner/android/utils/Utils.java
Constrain radius to 255 in cases where mission items implement NAV_LOITER_TURNS
> Fix Radius Overflow

- Android/res/menu/menu_drone_map.xml
- Android/res/values/strings.xml
- Android/src/org/droidplanner/android/fragments/DroneMap.java
- Android/src/org/droidplanner/android/fragments/FlightMapFragment.java
> Add a menu option to clear the drone flight path on the map

- Android/src/org/droidplanner/android/fragments/control/BaseFlightControlFragment.java
- Android/src/org/droidplanner/android/fragments/mode/ModeFollowFragment.java
- Android/src/org/droidplanner/android/utils/prefs/DroidPlannerPrefs.java
Small change to save the lastknownFollowMeMode i.e. the last one selected from the UI in the control box in preferences. Next time followme is selected the mode will be the same as this last used one.
> Save Last Known FollowMe mode in Preferences. 
